export interface TagDataType {
  classify: string;
  tags: { classify: string; tags: { value: string; label: string }[] }[];
}

export const tagData: TagDataType[] = [
  {
    classify: '常用',
    tags: [
      {
        classify: '优化Tag',
        tags: [
          { value: 'masterpiece', label: '大师作品' },
          { value: 'best quality', label: '最好画质' },
          {
            value:
              'masterpiece,best quality,official art,extremely detailed CG unity 8k wallpaper',
            label: '更高质量',
          },
        ],
      },
      {
        classify: '其它Tag',
        tags: [
          { value: 'wedding dress:china dress:0.3', label: '旗袍婚纱' },
          { value: 'arms behind head', label: '双手脑后' },
          { value: 'arms up, armpits', label: '举手露腋' },
          { value: 'tiamat (fate)', label: '提亚马特' },
        ],
      },
    ],
  },
  {
    classify: '环境',
    tags: [
      {
        classify: '朝朝暮暮',
        tags: [
          { value: 'day', label: '白天' },
          { value: 'dusk', label: '黄昏' },
          { value: 'night', label: '夜晚' },
          { value: 'in spring', label: '春' },
          { value: 'in summer', label: '夏' },
          { value: 'in autumn', label: '秋' },
          { value: 'in winter', label: '冬' },
        ],
      },
      {
        classify: '日月星辰',
        tags: [
          { value: 'sun', label: '太阳' },
          { value: 'sunset', label: '落日' },
          { value: 'moon', label: '月亮' },
          { value: 'full_moon', label: '满月' },
          { value: 'stars', label: '星星' },
          { value: 'cloudy', label: '多云' },
          { value: 'rain', label: '下雨' },
          { value: 'in the rain', label: '雨中' },
          { value: 'rainy days', label: '雨天' },
          { value: 'snow', label: '下雪' },
        ],
      },
      {
        classify: '天涯海角',
        tags: [
          { value: 'sky', label: '天空' },
          { value: 'sea', label: '大海' },
          { value: 'mountain', label: '山' },
          { value: 'on a hill', label: '山上' },
          { value: 'the top of the hill', label: '山顶' },
          { value: 'in a meadow', label: '草地' },
          { value: 'plateau', label: '高原' },
          { value: 'on a desert', label: '沙漠' },
          { value: 'in hawaii', label: '夏威夷' },
          { value: 'cityscape', label: '城市风景' },
          { value: 'landscape', label: '风景' },
          { value: 'beautiful detailed sky', label: '好天' },
          { value: 'beautiful detailed water', label: '好水' },
          { value: 'on the beach', label: '海滩上' },
          { value: 'on the ocean', label: '在大海上' },
          { value: 'over the sea', label: '海边上' },
          { value: 'over the sea', label: '海边上' },
          {
            value: 'beautiful purple sunset at beach',
            label: 'beautiful purple sunset at beach',
          },
          { value: 'in the ocean', label: '海边日落' },
          { value: 'against backlight at dusk', label: '傍晚背对阳光' },
          { value: 'golden hour lighting', label: '黄金时段照明' },
          { value: 'strong rim light', label: '强边缘光' },
          { value: 'intense shadows', label: '强阴影' },
          { value: 'fireworks', label: '焰火' },
          { value: 'flower field', label: '花田' },
          { value: 'underwater', label: '水下' },
          { value: 'explosion', label: '爆炸' },
          { value: 'in the cyberpunk city', label: '在赛博朋克城市' },
          { value: 'steam', label: '蒸汽' },
        ],
      },
    ],
  },
  {
    classify: '风格',
    tags: [
      {
        classify: '',
        tags: [
          { value: 'artbook', label: '原画' },
          { value: 'game_cg', label: '游戏CG' },
          { value: 'comic', label: '漫画' },
          { value: '4koma', label: '四格' },
          { value: 'animated_gifgif', label: '格式图片' },
          { value: 'dakimakura', label: '抱枕' },
          { value: 'cosplay', label: '角色扮演' },
          { value: 'crossover', label: '穿越' },
          { value: 'dark', label: '暗的' },
          { value: 'light', label: '亮的' },
          { value: 'night', label: '晚上' },
          { value: 'guro', label: '猎奇' },
          { value: 'realistic', label: '写实' },
          { value: 'photo', label: '照片' },
          { value: 'real', label: '真实' },
          { value: 'landscape/scenery', label: '风景' },
          { value: 'cityscape', label: '城市风景' },
          { value: 'science_fiction', label: '科技幻想' },
          { value: 'original', label: '原创' },
          { value: 'parody', label: '拙劣的模仿' },
          { value: 'personification', label: '拟人' },
          { value: 'checkered', label: '格子的' },
          { value: 'lowres', label: '低分辨率' },
          { value: 'highres', label: '高分辨率' },
          { value: 'absurdres', label: '超高分辨率' },
          { value: 'incredibly_absurdres', label: '极高分辨率' },
          { value: 'huge_filesize', label: '超级高分辨率/大文件' },
          { value: 'wallpaper', label: '壁纸' },
          { value: 'pixel_art', label: '点阵图' },
          { value: 'monochrome', label: '单色图片' },
          { value: 'colorful', label: '色彩斑斓的' },
          { value: 'optical_illusion', label: '视觉错误' },
          { value: 'fine_art_parody', label: '名画模仿' },
          { value: 'sketch', label: '素描' },
          { value: 'traditional_media', label: '传统媒体（基本上是手绘稿）' },
          { value: 'watercolor_(medium)', label: '透明水彩绘' },
          { value: 'silhouette', label: '剪影' },
          { value: 'covr', label: '封面' },
          { value: 'album', label: '专辑' },
          { value: 'sample', label: '图上有sample字样' },
          { value: 'back', label: '背影像' },
          { value: 'bust', label: '半身像' },
          { value: 'profile', label: '侧面绘' },
          { value: 'expressions', label: '表情绘（各种表情）' },
          { value: 'everyone', label: '一部作品中的主要人物集齐' },
          { value: 'column_lineup', label: '一列列小图组成大图' },
          { value: 'transparent_background', label: '透明的背景(.png)' },
          { value: 'simple_background', label: '简单的背景(无背景)' },
          { value: 'gradient_background', label: '渐变的背景' },
          { value: 'zoom_layer', label: '背景是前景的放大版' },
          { value: 'English', label: '英文' },
          { value: 'Chinese', label: '中文' },
          { value: 'French', label: '法文' },
          { value: 'Japanese', label: '日本人' },
          { value: 'translation_request', label: '翻译' },
          { value: 'bad_id', label: 'ID转向错误(原地址或已被删除)' },
          { value: 'tagme', label: '图片有一些上传者未知的项目' },
          { value: 'artist_request', label: '作者未知,需要补完' },
          { value: 'what', label: '不知所谓' },
        ],
      },
    ],
  },
  {
    classify: '人物&角色',
    tags: [
      {
        classify: '人物',
        tags: [
          { value: 'girl', label: '女孩' },
          { value: '2girls', label: '2女孩' },
          { value: '3girls', label: '3女孩' },
          { value: 'boy', label: '男孩' },
          { value: '2boys', label: '2男孩' },
          { value: '3boys', label: '3男孩' },
          { value: 'solo', label: '单人' },
          { value: 'multiple girls', label: '多个' },
          { value: 'little girl', label: '小女孩' },
          { value: 'little boy', label: '小男孩' },
          { value: 'shota', label: '正太' },
          { value: 'loli', label: '萝莉' },
          { value: 'kawaii', label: '可爱' },
          { value: 'mesugaki', label: '雌小鬼' },
          { value: 'adorable girl', label: '可爱的女孩' },
          { value: 'bishoujo', label: '美少女' },
          { value: 'gyaru', label: '辣妹' },
          { value: 'sisters', label: '姐妹' },
          { value: 'ojousama', label: '大小姐' },
          { value: 'mature female', label: '成熟女性' },
          { value: 'mature', label: '成熟' },
          { value: 'female pervert', label: '痴女' },
          { value: 'milf', label: '熟女' },
          { value: 'harem', label: '后宫' },
        ],
      },
      {
        classify: '角色',
        tags: [
          { value: 'angel', label: '天使' },
          { value: 'cheerleader', label: '啦啦队' },
          { value: 'chibi', label: 'Q版人物' },
          { value: 'crossdressing', label: '伪娘' },
          { value: 'devil', label: '魔鬼' },
          { value: 'doll', label: '人偶' },
          { value: 'elf', label: '妖精' },
          { value: 'fairy', label: '小精灵' },
          { value: 'female', label: '女人' },
          { value: 'furry', label: '兽人' },
          { value: 'orc', label: '半兽人' },
          { value: 'giantess', label: '女巨人' },
          { value: 'harem', label: '后宫' },
          { value: 'idol', label: '偶像' },
          { value: 'kemonomimi_mode', label: '兽耳萝莉模式' },
          { value: 'loli', label: '萝莉' },
          { value: 'magical_girl', label: '魔法少女' },
          { value: 'maid', label: '女仆' },
          { value: 'male', label: '男人' },
          { value: 'mermaid', label: '美人鱼' },
          { value: 'miko', label: '巫女' },
          { value: 'milf', label: '熟女' },
          { value: 'minigirl', label: '迷你女孩' },
          { value: 'monster', label: '怪物' },
          { value: 'multiple_girls', label: '魔幻少女' },
          { value: 'ninja', label: '忍者' },
          { value: 'no_humans', label: '非人' },
          { value: 'nun', label: '修女' },
          { value: 'nurse', label: '护士' },
          { value: 'shota', label: '正太' },
          { value: 'stewardess', label: '空姐' },
          { value: 'student', label: '学生' },
          { value: 'trap', label: '伪娘' },
          { value: 'vampire', label: '吸血鬼' },
          { value: 'waitress', label: '女服务员' },
          { value: 'witch', label: '女巫' },
          { value: 'yaoi', label: '搞基' },
          { value: 'yukkuri_shiteitte_ne', label: '油库里' },
          { value: 'yuri', label: '百合' },
        ],
      },
    ],
  },
  {
    classify: '头发&发饰',
    tags: [
      {
        classify: '长度',
        tags: [
          { value: 'very short hair', label: '很短' },
          { value: 'short hair', label: '短发' },
          { value: 'medium hair', label: '中发' },
          { value: 'long hair', label: '长发' },
          { value: 'very long hair', label: '很长' },
          { value: 'absurdly long hair', label: '特别长' },
          { value: 'hair over shoulder', label: '头发过肩' },
          { value: 'alternate hair length', label: '有长有短' },
        ],
      },
      {
        classify: '颜色',
        tags: [
          { value: 'blonde hair', label: '金色' },
          { value: 'brown hair', label: '棕色' },
          { value: 'black hair', label: '黑色' },
          { value: 'blue hair', label: '蓝色' },
          { value: 'purple hair', label: '紫色' },
          { value: 'pink hair', label: '粉红' },
          { value: 'white hair', label: '白色' },
          { value: 'red hair', label: '红色' },
          { value: 'grey hair', label: '灰色' },
          { value: 'green hair', label: '绿色' },
          { value: 'silver hair', label: '银色' },
          { value: 'orange hair', label: '橙色' },
          { value: 'light brown hair', label: '浅棕' },
          { value: 'light purple hair', label: '浅紫' },
          { value: 'light blue hair', label: '浅蓝' },
          { value: 'platinum blonde hair', label: '铂金色' },
          { value: 'gradient hair', label: '渐变' },
          { value: 'multicolored hair', label: '多色' },
          { value: 'shiny hair', label: '闪亮' },
          { value: 'two-tone hair', label: '双色' },
          { value: 'streaked hair', label: '挑染' },
          { value: 'aqua hair', label: '水色' },
          { value: 'colored inner hair', label: '内层彩发' },
          { value: 'alternate hair color', label: '交替发色' },
          { value: 'hair up', label: '头发起来' },
          { value: 'hair down', label: '头发下垂' },
          { value: 'wet hair', label: '湿头发' },
        ],
      },
      {
        classify: '发型',
        tags: [
          { value: 'ahoge', label: '呆毛' },
          { value: 'antenna hair', label: '多根呆毛' },
          { value: 'bob cut', label: '妹妹切' },
          { value: 'hime_cut', label: '公主切' },
          { value: 'crossed bangs', label: '交叉刘海' },
          { value: 'hair wings', label: '翼状头发' },
          { value: 'disheveled hair', label: '蓬发' },
          { value: 'wavy hair', label: '波浪头' },
          { value: 'curly_hair', label: '卷发' },
          { value: 'hair in takes', label: '收拢' },
          { value: 'forehead', label: '露额头' },
          { value: 'drill hair', label: '公主卷' },
          { value: 'hair bun', label: '包子头' },
          { value: 'double_bun', label: '俩包子头' },
          { value: 'straight hair', label: '直发' },
          { value: 'spiked hair', label: '尖刺的头发' },
          { value: 'short hair with long locks', label: '短发长鬓角' },
          { value: 'low-tied long hair', label: '低扎长发' },
          { value: 'asymmetrical hair', label: '不对称的头发' },
          { value: 'alternate hairstyle', label: '交替发型' },
          { value: 'big hair', label: '大头发' },
          { value: 'hair strand', label: '发丝' },
          { value: 'hair twirling', label: '卷发' },
          { value: 'pointy hair', label: '尖头头发' },
          { value: 'hair slicked back', label: '头发向后梳' },
          { value: 'hair pulled back', label: '头发向后拉' },
          { value: 'split-color hair', label: '分色头发' },
        ],
      },
      {
        classify: '发型',
        tags: [
          { value: 'braid', label: '辫子' },
          { value: 'twin braids', label: '双辫子' },
          { value: 'single braid', label: '单辫' },
          { value: 'side braid', label: '侧辫子' },
          { value: 'long braid', label: '长辫子' },
          { value: 'french braid', label: '法式辫子' },
          { value: 'crown braid', label: '皇冠编织' },
          { value: 'braided bun', label: '编织发髻' },
          { value: 'ponytail', label: '马尾辫' },
          { value: 'braided ponytail', label: '编马尾' },
          { value: 'high ponytail', label: '高马尾' },
          { value: 'twintails', label: '双马尾' },
          { value: 'short_ponytail', label: '短马尾' },
          { value: 'twin_braids', label: '双辫子' },
          { value: 'Side ponytail', label: '侧马' },
        ],
      },
      {
        classify: '刘海/其他',
        tags: [
          { value: 'bangs', label: '刘海' },
          { value: 'blunt bangs', label: '齐刘海' },
          { value: 'parted bangs', label: '分刘海' },
          { value: 'swept bangs', label: '侧扫刘海' },
          { value: 'crossed bangs', label: '交叉刘海' },
          { value: 'asymmetrical bangs', label: '不对称刘海' },
          { value: 'braided bangs', label: '辫子刘海' },
          { value: 'long bangs', label: '长刘海' },
          { value: 'bangs pinned back', label: '往后夹' },
          { value: 'diagonal bangs', label: '斜刘海' },
          { value: 'dyed bangs', label: '染刘海' },
          { value: 'hair between eyes', label: '眼睛之间的头发' },
          { value: 'hair over one eye', label: '一只眼睛上的头发' },
          { value: 'hair over eyes', label: '头发遮住眼睛' },
          { value: 'hair behind ear', label: '耳朵后面的头发' },
          { value: 'hair between breasts', label: '乳房之间的毛发' },
          { value: 'hair over breasts', label: '乳房上的头发' },
          { value: 'hair censor', label: '刘海+长发？' },
        ],
      },
      {
        classify: '发饰',
        tags: [
          { value: 'hair ornament', label: '发饰' },
          { value: 'hair bow', label: '蝴蝶结' },
          { value: 'hair ribbon', label: '发带' },
          { value: 'hairband', label: '发带' },
          { value: 'hair flower', label: '头花' },
          { value: 'hair bun', label: '发髻' },
          { value: 'hair bobbles', label: '毛球' },
          { value: 'hairclip', label: '发夹' },
          { value: 'single hair bun', label: '单发髻' },
          { value: 'x hair ornament', label: 'x发饰' },
          { value: 'black hairband', label: '黑色发带' },
          { value: 'hair scrunchie', label: '发箍' },
          { value: 'hair rings', label: '发圈' },
          { value: 'tied hair', label: '扎头发' },
          { value: 'hairpin', label: '发夹' },
          { value: 'white hairband', label: '白色发带' },
          { value: 'hair tie', label: '发带' },
          { value: 'frog hair ornament', label: '青蛙发饰' },
          { value: 'food-themed hair ornament', label: '食物发饰' },
          { value: 'tentacle hair', label: '触手头发' },
          { value: 'star hair ornament', label: '星星发饰' },
          { value: 'hair bell', label: '发铃' },
          { value: 'heart hair ornament', label: '心形发饰' },
          { value: 'red hairband', label: '红色发带' },
          { value: 'butterfly hair ornament', label: '蝴蝶发饰' },
          { value: 'hair stick', label: '发棒' },
          { value: 'snake hair ornament', label: '蛇发饰' },
          { value: 'lolita hairband', label: '洛丽塔发带' },
          { value: 'crescent hair ornament', label: '新月发饰' },
          { value: 'cone hair bun', label: '锥形发髻' },
          { value: 'feather hair ornament', label: '羽毛头饰' },
          { value: 'blue hairband', label: '蓝色发带' },
          { value: 'anchor hair ornament', label: '锚发饰' },
          { value: 'leaf hair ornament', label: '叶发饰' },
          { value: 'bunny hair ornament', label: '兔子头饰' },
          { value: 'skull hair ornament', label: '骷髅头饰' },
          { value: 'yellow hairband', label: '黄色发带' },
          { value: 'pink hairband', label: '粉色发带' },
          { value: 'dark blue hair', label: '深蓝色头发' },
          { value: 'bow hairband', label: '蝴蝶结发带' },
          { value: 'cat hair ornament', label: '猫头饰' },
          { value: 'musical note hair ornament', label: '音符发饰' },
          { value: 'carrot hair ornament', label: '胡萝卜发饰' },
          { value: 'purple hairband', label: '紫色发带' },
          { value: 'hair tucking', label: '头发掖' },
          { value: 'hair beads', label: '发珠' },
          { value: 'multiple hair bows', label: '多个蝴蝶结' },
          { value: 'hairpods', label: '发夹' },
          { value: 'bat hair ornament', label: '蝙蝠发饰' },
          { value: 'bone hair ornament', label: '骨发饰' },
          { value: 'orange hairband', label: '橙色发带' },
          { value: 'multi-tied hair', label: '多扎头发' },
          { value: 'snowflake hair ornament', label: '雪花发饰' },
        ],
      },
    ],
  },
  {
    classify: '五官&表情',
    tags: [
      {
        classify: '',
        tags: [
          { value: 'food on face', label: '食物在脸上（食物可替换）' },
          { value: 'light blush', label: '淡淡腮红' },
          { value: 'facepaint', label: '面纹' },
          { value: 'makeup', label: '浓妆' },
          { value: 'cute face', label: '可爱表情' },
          { value: 'white colored eyelashes', label: '白色睫毛' },
          { value: 'longeyelashes', label: '长睫毛' },
          { value: 'white eyebrows', label: '白色眉毛' },
          { value: 'tsurime', label: '吊眼角' },
          { value: 'gradient_eyes', label: '渐变眼' },
          { value: 'beautiful detailed eyes', label: '美丽的细节眼睛' },
          { value: 'tareme', label: '垂眼角' },
          { value: 'slit pupils', label: '猫眼' },
          { value: 'heterochromia', label: '异色瞳' },
          { value: 'heterochromia blue red', label: '红蓝眼' },
          { value: 'aqua eyes', label: '水汪汪大眼' },
          { value: 'looking at viewer', label: '看你' },
          { value: 'eyeball', label: '盯着看' },
          { value: 'stare', label: '凝视' },
          { value: 'visible through hair', label: '透过刘海看' },
          { value: 'looking to the side', label: '看旁边' },
          { value: 'constricted pupils', label: '收缩的瞳孔' },
          { value: 'symbol-shaped pupils', label: '符号形状的瞳孔' },
          { value: 'heart in eye', label: '爱心状眼睛' },
          { value: 'heart-shaped pupils', label: '爱心瞳孔' },
          { value: 'wink', label: '眨眼' },
          { value: 'mole under eye', label: '眼下痣' },
          { value: 'eyes closed', label: '闭眼' },
          { value: 'no_nose', label: '没鼻子' },
          { value: 'fake animal ears', label: '动物耳朵' },
          { value: 'animal ear fluff', label: '动物耳绒毛' },
          { value: 'animal_ears', label: '动物耳朵' },
          { value: 'fox_ears', label: '狐狸耳朵' },
          { value: 'bunny_ears', label: '兔子耳朵' },
          { value: 'cat_ears', label: '猫耳' },
          { value: 'dog_ears', label: '狗耳' },
          { value: 'mouse_ears', label: '鼠耳' },
          { value: 'hair ear', label: '头发上耳朵' },
          { value: 'pointy ears', label: '尖耳' },
          { value: 'light smile', label: '微笑' },
          { value: 'seductive smile', label: '诱惑笑' },
          { value: 'grin', label: '露齿而笑' },
          { value: 'laughing', label: '笑' },
          { value: 'teeth', label: '牙' },
          { value: 'excited', label: '兴奋' },
          { value: 'embarrassed', label: '害羞' },
          { value: 'blush', label: '脸红' },
          { value: 'shy', label: '害羞' },
          { value: 'nose blush', label: '鼻子脸红' },
          { value: 'expressionless', label: '无表情' },
          { value: 'expressionless eyes', label: '失神' },
          { value: 'sleepy', label: '困' },
          { value: 'drunk', label: '喝醉的' },
          { value: 'tears', label: '哭' },
          { value: 'crying with eyes open', label: '睁着眼哭' },
          { value: 'sad', label: '悲伤的' },
          { value: 'pout', label: '别扭 努嘴' },
          { value: 'sigh', label: '叹气' },
          { value: 'wide eyed', label: '睁大眼睛' },
          { value: 'angry', label: '生气' },
          { value: 'annoyed', label: '苦恼的' },
          { value: 'frown', label: '皱眉' },
          { value: 'smirk', label: '认真' },
          { value: 'serious', label: '严肃' },
          { value: 'jitome', label: '鄙夷' },
          { value: 'scowl', label: '锐利' },
          { value: 'crazy', label: '疯狂的' },
          { value: 'dark_persona', label: '黑化的' },
          { value: 'smirk', label: '微笑' },
          { value: 'smug', label: '得意' },
          { value: 'naughty_face', label: '调皮脸' },
          { value: 'one eye closed', label: '一只眼睛闭上' },
          { value: 'half-closed eyes', label: '半闭眼睛' },
          { value: 'nosebleed', label: '鼻血' },
          { value: 'eyelid pull', label: '做鬼脸' },
          { value: 'tongue', label: '舌头' },
          { value: 'tongue out', label: '吐舌' },
          { value: 'closed mouth', label: '闭嘴' },
          { value: 'open mouth', label: '张嘴' },
          { value: 'lipstick', label: '口红' },
          { value: 'fangs', label: '尖牙' },
          { value: 'clenched teeth', label: '咬紧牙关' },
          { value: ':3', label: 'ω猫嘴' },
          { value: ':p', label: '向下吐舌头' },
          { value: ':q', label: '向上吐舌头' },
          { value: ':t', label: '不耐烦' },
          { value: ':d', label: '杯型笑脸' },
        ],
      },
    ],
  },
  {
    classify: '眼睛',
    tags: [
      {
        classify: '颜色',
        tags: [
          { value: 'blue eyes', label: '蓝色' },
          { value: 'red eyes', label: '红色' },
          { value: 'brown eyes', label: '棕色' },
          { value: 'green eyes', label: '绿色' },
          { value: 'purple eyes', label: '紫色' },
          { value: 'yellow eyes', label: '黄色' },
          { value: 'pink eyes', label: '粉红' },
          { value: 'black eyes', label: '黑色' },
          { value: 'aqua eyes', label: '水蓝色' },
          { value: 'orange eyes', label: '橙色' },
          { value: 'grey eyes', label: '灰色' },
          { value: 'multicolored eyes', label: '五彩' },
          { value: 'white eyes', label: '白色' },
          { value: 'gradient eyes', label: '渐变' },
        ],
      },
      {
        classify: '状态',
        tags: [
          { value: 'closed eyes', label: '闭上眼睛' },
          { value: 'half-closed eyes', label: '半闭眼' },
          { value: 'crying with eyes open', label: '睁着眼睛哭' },
          { value: 'narrowed eyes', label: '眯起眼睛' },
          { value: 'hidden eyes', label: '隐藏的眼睛' },
          { value: 'heart-shaped eyes', label: '心形眼睛' },
          { value: 'button eyes', label: '纽扣眼' },
          { value: 'cephalopod eyes', label: '头足类眼睛' },
          { value: 'eyes visible through hair', label: '透过头发看见眼睛' },
          { value: 'glowing eyes', label: '发光的眼睛' },
          { value: 'empty eyes', label: '空洞的眼睛' },
          { value: 'rolling eyes', label: '翻白眼' },
          { value: 'blank eyes', label: '空白的眼睛' },
          { value: 'no eyes', label: '没有眼睛' },
          { value: 'sparkling eyes', label: '闪闪发光的眼睛' },
          { value: 'extra eyes', label: '额外的眼睛' },
          { value: 'crazy eyes', label: '疯狂的眼睛' },
          { value: 'solid circle eyes', label: '实心圆眼' },
          { value: 'uneven eyes', label: '不均匀的眼睛' },
          { value: 'blood from eyes', label: '眼睛里的血' },
        ],
      },
      {
        classify: '其他',
        tags: [
          { value: 'eyeshadow', label: '眼影' },
          { value: 'red eyeshadow', label: '红色眼影' },
          { value: 'blue eyeshadow', label: '蓝色眼影' },
          { value: 'purple eyeshadow', label: '紫色眼影' },
          { value: 'pink eyeshadow', label: '粉色眼影' },
          { value: 'green eyeshadow', label: '绿色眼影' },
          { value: 'bags under eyes', label: '眼袋' },
          { value: 'ringed eyes', label: '眼圈' },
          { value: 'covered eyes', label: '蒙住眼睛' },
          { value: 'covering eyes', label: 'covering遮住眼睛' },
          { value: 'shading eyes', label: 'shading遮住眼睛' },
        ],
      },
    ],
  },
  {
    classify: '身体',
    tags: [
      {
        classify: '',
        tags: [
          { value: 'breasts', label: '胸' },
          { value: 'small breasts', label: '小' },
          { value: 'medium breasts', label: '中' },
          { value: 'large breasts', label: '大' },
          { value: 'huge breasts', label: '超大' },
          { value: 'alternate breast size', label: '不同尺寸' },
          { value: 'mole on breast', label: '乳房上有痣' },
          { value: 'between breasts', label: '两胸之间' },
          { value: 'breasts apart', label: '胸部分开' },
          { value: 'hanging breasts', label: '晃来晃去' },
          { value: 'bouncing breasts', label: '弹来弹去' },
        ],
      },
    ],
  },
  {
    classify: '服装',
    tags: [
      {
        classify: '衣服',
        tags: [
          { value: 'sailor collar', label: '领子' },
          { value: 'hat', label: '帽子' },
          { value: 'shirt', label: '衬衫' },
          { value: 'serafuku', label: 'serafuku水手服' },
          { value: 'sailor suite', label: 'sailor suite水手服' },
          { value: 'sailor shirt', label: 'sailor shirt水手服' },
          { value: 'shorts under skirt', label: 'shorts under skirt水手服' },
          { value: 'collared shirt', label: '有领衬衣' },
          { value: 'school uniform', label: '学校制服' },
          { value: 'seifuku', label: '日本学生服' },
          { value: 'business_suit', label: '职场制服' },
          { value: 'jacket', label: '夹克' },
          { value: 'suit', label: '西装' },
          { value: 'garreg mach monastery uniform', label: '火焰纹章军服' },
          { value: 'revealing dress', label: '礼服长裙' },
          { value: 'pink lucency full dress', label: '礼服' },
          { value: 'cleavage dress', label: '露出胸口部分的连衣裙' },
          { value: 'sleeveless dress', label: '无袖连衣裙' },
          { value: 'whitedress', label: '白色连衣裙' },
          { value: 'wedding_dress', label: '婚纱' },
          { value: 'Sailor dress', label: '水手连衣裙' },
          { value: 'sweater dress', label: '毛衣裙' },
          { value: 'ribbed sweater', label: '罗纹毛衣' },
          { value: 'sweater jacket', label: '毛衣夹克' },
          { value: 'dungarees', label: '工装服' },
          { value: 'brown cardigan', label: '棕色开襟衫（外套）' },
          { value: 'hoodie', label: '连帽衫，卫衣' },
          { value: 'robe', label: '长袍' },
          { value: 'cape', label: '斗篷' },
          { value: 'cardigan', label: '羊毛衫' },
          { value: 'apron', label: '围裙' },
          { value: 'gothic', label: '哥特风格' },
          { value: 'lolita_fashion', label: '洛丽塔风格' },
          { value: 'gothic_lolita', label: '哥特洛丽塔风格' },
          { value: 'western', label: '西部风格' },
          { value: 'tartan', label: '格子花纹' },
          { value: 'off_shoulder', label: '露单肩' },
          { value: 'bare_shoulders', label: '露双肩' },
          { value: 'barefoot', label: '赤脚' },
          { value: 'bare_legs', label: '裸足' },
          { value: 'striped', label: '横条花纹的' },
          { value: 'polka_dot', label: '点状花纹的' },
          { value: 'frills', label: '皱边的' },
          { value: 'lace', label: '花边' },
          { value: 'buruma', label: '日本女生运动短裤' },
          { value: 'sportswear', label: 'sportswear运动服' },
          { value: 'gym_uniform', label: 'gym_uniform运动服' },
          { value: 'tank_top', label: '女用背心' },
          { value: 'cropped jacket', label: '裁剪短夹克' },
          { value: 'black sports bra', label: '运动胸罩' },
          { value: 'crop top', label: '漏脐装' },
          { value: 'pajamas', label: '睡衣' },
          { value: 'japanese_clothes', label: '和服' },
          { value: 'obi', label: '衣带(和服用)' },
          { value: 'mesh', label: '网眼上衣' },
          { value: 'sleeveless shirt', label: '无袖上衣' },
          { value: 'detached_sleeves', label: '袖肩分离装' },
          { value: 'white bloomers', label: '白色灯笼裤' },
          { value: 'high - waist shorts', label: '高腰腿裤' },
          { value: 'pleated_skirt', label: '百褶裙' },
          { value: 'skirt', label: '裙子' },
          { value: 'miniskirt', label: '迷你裙' },
          { value: 'short shorts', label: '热裤' },
          { value: 'summer_dress', label: '夏日长裙' },
          { value: 'bloomers', label: '灯笼裤' },
          { value: 'shorts', label: '短裤' },
          { value: 'bike_shorts', label: '自行车短裤' },
          { value: 'dolphin shorts', label: '海豚短裤' },
          { value: 'belt', label: '腰带' },
          { value: 'bikini', label: '比基尼' },
          { value: 'sling bikini', label: '吊索比基尼' },
          { value: 'bikini_top', label: '比基尼乳罩' },
          { value: 'bikini top only', label: '上身比基尼' },
          { value: 'side - tie bikini bottom', label: '侧边系带比基尼下装' },
          { value: 'side-tie_bikini', label: '系带式比基尼' },
          { value: 'friled bikini', label: '褶边比基尼' },
          { value: 'bikini under clothes', label: '比基尼内衣' },
          { value: 'swimsuit', label: '泳装' },
          { value: 'school swimsuit', label: '学校泳衣' },
          { value: 'one-piece swimsuit', label: '连体泳衣' },
          { value: 'competition swimsuit', label: '竞技泳衣' },
          { value: 'Sukumizu', label: '死库水' },
        ],
      },
    ],
  },
  {
    classify: '袜子&腿饰',
    tags: [
      {
        classify: '袜子',
        tags: [
          { value: 'bare legs', label: '裸腿' },
          { value: 'garter straps', label: 'straps吊袜带' },
          { value: 'garter belt', label: 'belt吊袜带' },
          { value: 'socks', label: '袜子' },
          { value: 'kneehighs', label: '过膝袜' },
          { value: 'white kneehighs', label: '白色过膝袜' },
          { value: 'black kneehighs', label: '黑色过膝袜' },
          { value: 'over-kneehighs', label: '过膝袜' },
          { value: 'single kneehigh', label: '单只过膝袜' },
          { value: 'tabi', label: '日式厚底短袜' },
          { value: 'bobby socks', label: '短袜' },
          { value: 'loose socks', label: '堆堆袜' },
          { value: 'single sock', label: '单袜' },
          { value: 'no socks', label: '没有袜子' },
          { value: 'socks removed', label: '脱掉袜子' },
          { value: 'ankle socks', label: '及踝袜' },
          { value: 'striped socks', label: '条纹袜' },
          { value: 'blue socks', label: '蓝袜子' },
          { value: 'grey socks', label: '灰袜子' },
          { value: 'red socks', label: '红袜子' },
          { value: 'frilled socks', label: '荷叶边袜子' },
        ],
      },
      {
        classify: '长筒袜',
        tags: [
          { value: 'thighhighs', label: '长筒袜' },
          { value: 'black thighhighs', label: '黑色长筒袜' },
          { value: 'white thighhighs', label: '白色长筒袜' },
          { value: 'striped thighhighs', label: '条纹长筒袜' },
          { value: 'brown thighhighs', label: '棕色长筒袜' },
          { value: 'blue thighhighs', label: '蓝色长筒袜' },
          { value: 'red thighhighs', label: '红色长筒袜' },
          { value: 'purple thighhighs', label: '紫色长筒袜' },
          { value: 'pink thighhighs', label: '粉色长筒袜' },
          { value: 'grey thighhighs', label: '灰色长筒袜' },
          { value: 'thighhighs under boots', label: '靴子长筒袜' },
          { value: 'green thighhighs', label: '绿色长筒袜' },
          { value: 'yellow thighhighs', label: '黄色长筒袜' },
          { value: 'orange thighhighs', label: '橙色长筒袜' },
          { value: 'vertical-striped thighhighs', label: '竖条纹长筒袜' },
          { value: 'frilled thighhighs', label: '褶边长筒袜' },
          { value: 'fishnet thighhighs', label: '渔网长筒袜' },
        ],
      },
      {
        classify: '连裤袜',
        tags: [
          { value: 'pantyhose', label: '连裤袜' },
          { value: 'black pantyhose', label: '黑色连裤袜' },
          { value: 'white pantyhose', label: '白色连裤袜' },
          { value: 'thighband pantyhose', label: '绑腿连裤袜' },
          { value: 'brown pantyhose', label: '棕色连裤袜' },
          { value: 'fishnet pantyhose', label: '渔网连裤袜' },
          { value: 'striped pantyhose', label: 'striped竖条纹连裤袜' },
          {
            value: 'vertical-striped pantyhose',
            label: 'vertical-striped竖条纹连裤袜',
          },
          { value: 'grey pantyhose', label: '灰色连裤袜' },
          { value: 'blue pantyhose', label: '蓝色连裤袜' },
          { value: 'single leg pantyhose', label: '单腿连裤袜' },
          { value: 'purple pantyhose', label: '紫色连裤袜' },
          { value: 'red pantyhose', label: '红色连裤袜' },
          { value: 'fishnet legwear', label: '渔网袜' },
        ],
      },
      {
        classify: '腿饰&组合',
        tags: [
          { value: 'bandaged leg', label: '包扎腿' },
          { value: 'bandaid on leg', label: '腿上的绷带' },
          { value: 'mechanical legs', label: '机械腿' },
          { value: 'leg belt', label: '腿带' },
          { value: 'leg tattoo', label: '腿部纹身' },
          { value: 'bound legs', label: '绑腿' },
          { value: 'leg lock', label: '腿锁' },
          { value: 'panties under pantyhose', label: '连裤袜下的内裤' },
          {
            value: 'panty & stocking with garterbelt',
            label: '吊袜带内裤和长袜',
          },
          { value: 'thighhighs over pantyhose', label: '连裤袜加长筒袜' },
          { value: 'socks over thighhighs', label: '长筒袜加短袜' },
          { value: 'panties over pantyhose', label: '连裤袜上的内裤' },
          { value: 'pantyhose under swimsuit', label: '泳衣下连裤袜' },
          { value: 'black garter belt', label: '黑色吊袜带' },
          { value: 'neck garter', label: '吊袜带' },
          { value: 'white garter straps', label: '白色吊袜带' },
          { value: 'black garter straps', label: '黑色吊袜带' },
          { value: 'ankle garter', label: '脚踝吊袜带' },
        ],
      },
      {
        classify: '裤袜',
        tags: [
          { value: 'no legwear', label: '裸腿' },
          { value: 'black legwear', label: '黑色裤袜' },
          { value: 'white legwear', label: '白色裤袜' },
          { value: 'torn legwear', label: '撕裂的裤袜' },
          { value: 'striped legwear', label: '条纹裤袜' },
          { value: 'asymmetrical legwear', label: '不对称裤腿' },
          { value: 'brown legwear', label: '棕色裤袜' },
          { value: 'uneven legwear', label: '不均匀的裤腿' },
          { value: 'toeless legwear', label: '无趾裤袜' },
          { value: 'print legwear', label: '印花裤袜' },
          { value: 'lace-trimmed legwear', label: '蕾丝边裤' },
          { value: 'red legwear', label: '红色裤袜' },
          { value: 'mismatched legwear', label: '不匹配的腿饰' },
          { value: 'legwear under shorts', label: '短裤下的裤袜' },
          { value: 'purple legwear', label: '紫色裤袜' },
          { value: 'grey legwear', label: '灰色裤袜' },
          { value: 'blue legwear', label: '蓝色裤袜' },
          { value: 'pink legwear', label: '粉色裤袜' },
          { value: 'argyle legwear', label: '菱形裤腿' },
          { value: 'ribbon-trimmed legwear', label: '丝带边饰裤袜' },
          { value: 'american flag legwear', label: '星条旗裤袜' },
          { value: 'green legwear', label: '绿色裤袜' },
          { value: 'vertical-striped legwear', label: '竖条纹裤袜' },
          { value: 'frilled legwear', label: '褶边裤袜' },
          { value: 'stirrup legwear', label: '马镫腿裤' },
          { value: 'alternate legwear', label: '备用裤袜' },
          { value: 'seamed legwear', label: '接缝裤袜' },
          { value: 'yellow legwear', label: '黄色裤袜' },
          { value: 'multicolored legwear', label: '五彩裤袜' },
          { value: 'ribbed legwear', label: '罗纹裤袜' },
          { value: 'fur-trimmed legwear', label: '毛皮裤袜' },
          { value: 'see-through legwear', label: '透视裤袜' },
          { value: 'legwear garter', label: '裤袜吊袜带' },
          { value: 'two-tone legwear', label: '双色裤袜' },
          { value: 'latex legwear', label: '乳胶裤袜' },
        ],
      },
    ],
  },
  {
    classify: '鞋',
    tags: [
      {
        classify: '鞋子',
        tags: [
          { value: 'shoes', label: '鞋子' },
          { value: 'boots', label: '靴子' },
          { value: 'loafers', label: '乐福鞋' },
          { value: 'high heels', label: '高跟鞋' },
          { value: 'cross-laced_footwear', label: '系带靴' },
          { value: 'mary_janes', label: '玛丽珍鞋' },
          { value: 'uwabaki', label: '女式学生鞋' },
          { value: 'slippers', label: '拖鞋' },
          { value: 'knee_boots', label: '马靴' },
        ],
      },
    ],
  },
  {
    classify: '装饰',
    tags: [
      {
        classify: '装饰',
        tags: [
          { value: 'halo', label: '光环' },
          { value: 'mini_top_hat', label: '迷你礼帽' },
          { value: 'beret', label: '贝雷帽' },
          { value: 'hood', label: '兜帽' },
          { value: 'nurse cap', label: '护士帽' },
          { value: 'tiara', label: '皇冠' },
          { value: 'oni horns', label: '鬼角' },
          { value: 'demon horns', label: '恶魔角' },
          { value: 'hair ribbon', label: '发带' },
          { value: 'flower ribbon', label: '花丝带' },
          { value: 'hairband', label: '发卡' },
          { value: 'hairclip', label: '发夹' },
          { value: 'hair_ribbon', label: '发带' },
          { value: 'hair_flower', label: '发花' },
          { value: 'hair_ornament', label: '头饰' },
          { value: 'bowtie', label: '蝴蝶结' },
          { value: 'hair_bow', label: '蝴蝶结发饰' },
          { value: 'maid_headdress', label: '女仆头饰' },
          { value: 'bow', label: '服装饰品/头部饰品' },
          { value: 'hair ornament', label: '发饰' },
          { value: 'heart hair ornament', label: '心形' },
          { value: 'bandaid hair ornament', label: '创可贴' },
          { value: 'hair bun', label: '发包' },
          { value: 'cone hair bun', label: '锥形发髻' },
          { value: 'double bun', label: '双发髻' },
          { value: 'semi-rimless eyewear', label: '半无框的眼镜' },
          { value: 'sunglasses', label: '太阳镜' },
          { value: 'goggles', label: '风镜' },
          { value: 'eyepatch', label: '眼罩(独眼)' },
          { value: 'black blindfold', label: '黑色眼罩' },
          { value: 'headphones', label: '耳机' },
          { value: 'veil', label: '面纱' },
          { value: 'mouth mask', label: '口罩' },
          { value: 'glasses', label: '眼镜' },
          { value: 'earrings', label: '耳环' },
          { value: 'jewelry', label: '首饰' },
          { value: 'bell', label: '铃铛' },
          { value: 'ribbon_choker', label: '颈带' },
          { value: 'black choker', label: '颈部饰品' },
          { value: 'necklace', label: '项链' },
          { value: 'headphones around neck', label: '耳机套脖子上' },
          { value: 'collar', label: '项圈' },
          { value: 'sailor_collar', label: '水手领' },
          { value: 'neckerchief', label: '领巾' },
          { value: 'necktie', label: '领带' },
          { value: 'cross necklace', label: '十字架' },
          { value: 'pendant', label: '吊坠' },
          { value: 'jewelry', label: '珠宝' },
          { value: 'scarf', label: '围巾' },
          { value: 'armband', label: '臂章' },
          { value: 'armlet', label: '臂环' },
          { value: 'arm strap', label: '臂带' },
          { value: 'elbow gloves', label: '肘部手套' },
          { value: 'half gloves', label: '露指手套' },
          { value: 'fingerless_gloves', label: '手镯' },
          { value: 'gloves', label: '手套' },
          { value: 'fingerless gloves', label: '五指手套' },
          { value: 'chains', label: '锁链' },
          { value: 'shackles', label: '手链' },
          { value: 'cuffs', label: '手铐' },
          { value: 'handcuffs', label: '手铐' },
          { value: 'bracelet', label: '手镯' },
          { value: 'wristwatch', label: '手表' },
          { value: 'wristband', label: '腕带' },
          { value: 'wrist_cuffs', label: '腕饰' },
          { value: 'holding book', label: '拿着书' },
          { value: 'holding sword', label: '拿着剑' },
          { value: 'tennis racket', label: '球拍' },
          { value: 'cane', label: '手杖' },
          { value: 'backpack', label: '双肩包' },
          { value: 'school bag', label: '书包' },
          { value: 'satchel', label: '肩背书包' },
          { value: 'smartphone', label: '手机' },
          { value: 'bandaid', label: '创可贴' },
        ],
      },
    ],
  },
  {
    classify: '动作',
    tags: [
      {
        classify: '动作',
        tags: [
          { value: 'head tilt', label: '歪头' },
          { value: 'turning around', label: 'turning around回头' },
          { value: 'looking back', label: 'looking back回头' },
          { value: 'looking down', label: '向下看' },
          { value: 'looking up', label: '向上看' },
          { value: 'smelling', label: '闻' },
          { value: 'hand_to_mouth', label: '手放在嘴边' },
          { value: 'arm at side ', label: '手放头旁边' },
          { value: 'arms behind head', label: '手放脑后' },
          { value: 'arms behind back ', label: '手放后面' },
          { value: 'hand on own chest', label: '手放在自己的胸前' },
          { value: 'arms_crossed', label: '手交叉于胸前' },
          { value: 'hand on hip', label: '手放臀' },
          { value: "hand on another's hip", label: '手放臀' },
          { value: 'hand_on_hip', label: '单手插腰' },
          { value: 'hands_on_hips', label: '双手叉腰' },
          { value: 'arms up', label: '举手' },
          { value: 'hands up', label: '举手' },
          { value: 'stretch', label: '伸懒腰' },
          { value: 'armpits', label: '举手露腋' },
          { value: 'leg hold', label: '手把腿抓着' },
          { value: 'grabbing', label: '抓住' },
          { value: 'holding', label: '拿着' },
          { value: 'fingersmile', label: '用手指做出笑脸' },
          { value: 'hair_pull', label: '拉头发' },
          { value: 'hair scrunchie', label: '撮头发' },
          { value: 'w', label: '手势' },
          { value: 'v', label: 'v耶' },
          { value: 'peace symbol', label: 'peace symbol耶' },
          { value: 'thumbs_up', label: '翘大拇指' },
          { value: 'middle_finger', label: '比出中指' },
          { value: 'cat_pose', label: '猫爪手势' },
          { value: 'finger_gun', label: '手枪手势' },
          { value: 'shushing', label: '嘘手势' },
          { value: 'waving', label: '招手' },
          { value: 'salute', label: '敬礼' },
          { value: 'spread_arms', label: '张手' },
          { value: 'spread legs', label: '张开腿' },
          { value: 'crossed_legs', label: '二郎腿' },
          { value: 'fetal_position', label: '曲腿至胸' },
          { value: 'leg_lift', label: '抬一只脚' },
          { value: 'legs_up', label: '抬两只脚' },
          { value: 'leaning forward ', label: '前倾' },
          { value: 'fetal position', label: '婴儿姿势' },
          { value: 'against wall', label: '靠墙' },
          { value: 'on_stomach', label: '趴着' },
          { value: 'squatting', label: '蹲下' },
          { value: 'lying', label: '躺着' },
          { value: 'sitting', label: 'sitting坐' },
          { value: 'sitting on', label: 'sitting on坐' },
          { value: 'seiza', label: '正坐' },
          { value: 'wariza/w-sitting', label: '割坐' },
          { value: 'yokozuwari', label: '侧身坐' },
          { value: 'indian_style', label: '盘腿' },
          { value: 'leg_hug', label: '抱腿' },
          { value: 'walking', label: '走' },
          { value: 'running', label: '跑' },
          { value: 'straddle', label: 'straddle跨坐' },
          { value: 'straddling', label: 'straddling跨坐' },
          { value: 'kneeling', label: '下跪' },
          { value: 'smoking', label: '抽烟' },
          { value: 'arm_support', label: '用手支撑住' },
          { value: 'caramelldansen', label: 'niconiconi' },
          { value: 'princess_carry', label: '公主抱' },
          { value: 'fighting_stance', label: '战斗姿态' },
          { value: 'upside-down', label: '颠倒的' },
          { value: 'top-down_bottom-up', label: '趴着翘臀' },
          { value: 'bent_over', label: '翘臀姿势' },
          { value: 'arched_back', label: '弓身体' },
          { value: 'back-to-back', label: '背对背' },
          { value: 'symmetrical_hand_pose', label: '手对手' },
          { value: 'eye_contact', label: '眼对眼（对视）' },
          { value: 'hug', label: '拥抱' },
          { value: 'lap_pillow', label: '膝枕' },
          { value: 'sleeping', label: '睡觉' },
          { value: 'bathing', label: '洗澡' },
          { value: 'mimikaki', label: '掏耳勺' },
          { value: 'holding_hands', label: '牵手' },
        ],
      },
      {
        classify: '头发相关',
        tags: [
          { value: 'hair blowing', label: '吹头发' },
          { value: 'adjusting hair', label: '调整头发' },
          { value: 'hand in own hair', label: '手牵自己的头发' },
          { value: 'holding hair', label: '握头发' },
          { value: 'tying hair', label: '扎头发' },
          { value: "grabbing another's hair", label: '抓别人的头发' },
          { value: 'hands in hair', label: '手在头发' },
          { value: 'brushing hair', label: '梳头' },
          { value: 'washing hair', label: '洗头' },
        ],
      },
    ],
  },
];
